Refactor configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,34 +1,67 @@
-# Use backticks to be bourne compliant
-PKGCONFIG=`command -v pkg-config`
+#!/bin/bash
+# Anticonf (tm) script by Jeroen Ooms (2015)
+# This script will query 'pkg-config' for the required cflags and ldflags.
+# If pkg-config is unavailable or does not find the library, try setting
+# INCLUDE_DIR and LIB_DIR manually via e.g:
+# R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
 
-# Custom libxml2 path for compatibility with old XML package
-if [ "$LIBXML_INCDIR" ]; then
-  LIBXML_CFLAGS="-I$LIBXML_INCDIR"
-  echo "User specified xml2 headers in $LIBXML_INCDIR."
-elif [ "$PKGCONFIG" ]; then
-  LIBXML_CFLAGS=`pkg-config --cflags libxml-2.0`
-  LIBXML_LIBS=`pkg-config --libs libxml-2.0`
-elif [ -r "/opt/csw/include/libxml2/libxml/parser.h" ]; then
-  LIBXML_CFLAGS="-I/opt/csw/include/libxml2/"
-  LIBXML_LIBS="-L/opt/csw/lib/ -lxml2"
-elif [ -r "/usr/include/libxml2/libxml/parser.h" ]; then
-  LIBXML_CFLAGS="-I/usr/include/libxml2/"
-elif [ -r "/usr/local/include/libxml2/libxml/parser.h" ]; then
-  LIBXML_CFLAGS="-I/usr/local/include/libxml2/"
+# Library settings
+PKG_CONFIG_NAME="libxml-2.0"
+PKG_DEB_NAME="libxml2-dev"
+PKG_RPM_NAME="libxml2-devel"
+PKG_CSW_NAME="libxml2_dev"
+PKG_TEST_HEADER="<libxml/tree.h>"
+PKG_LIBS="-lxml2"
+
+# Use xml2-config if available
+if [ $(command -v xml2-config) ]; then
+  PKGCONFIG_CFLAGS=$(xml2-config --cflags)
+  PKGCONFIG_LIBS=$(xml2-config --libs)
+elif [ $(command -v pkg-config) ]; then
+  PKGCONFIG_CFLAGS=$(pkg-config --cflags $PKG_CONFIG_NAME)
+  PKGCONFIG_LIBS=$(pkg-config --libs $PKG_CONFIG_NAME)
 fi
 
-if [ "$LIBXML_CFLAGS" ]; then
-  echo "PKG_CPPFLAGS= $LIBXML_CFLAGS" > src/Makevars
-  echo "Found libxml2 in $LIBXML_CFLAGS"
-else
-  echo "Could not find libxml2. Please install libxml2-devel (rpm) or libxml2-dev (deb)."
-  exit 1
+# Note that cflags may be empty in case of success
+if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
+  echo "Found INCLUDE_DIR and/or LIB_DIR!"
+  PKG_CFLAGS="-I$INCLUDE_DIR $PKG_CFLAGS"
+  PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
+elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
+  echo "Found pkg-config cflags and libs!"
+  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
+  PKG_LIBS=${PKGCONFIG_LIBS}
 fi
 
-if [ "$LIBXML_LIBS" ]; then
-  echo "PKG_LIBS= $LIBXML_LIBS" >> src/Makevars
-else
-  echo "PKG_LIBS= -lxml2" >> src/Makevars
+# Find compiler
+CC=$(${R_HOME}/bin/R CMD config CC)
+CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
+CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
+
+# For debugging
+echo "Using PKG_CFLAGS=$PKG_CFLAGS"
+echo "Using PKG_LIBS=$PKG_LIBS"
+
+# Test configuration
+echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
+
+# Customize the error
+if [ $R_CONFIG_ERROR ]; then
+  echo "------------------------- ANTICONF ERROR ---------------------------"
+  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
+  echo " * csw: $PKG_CSW_NAME (Solaris)"
+  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
+  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+  echo "--------------------------------------------------------------------"
+  exit 1;
 fi
 
+# Write to Makevars
+sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+
+# Success
 exit 0
