Fix configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,33 +1,27 @@
 # Custom libxml2 path for compatibility with old XML package
 if [ "$LIBXML_INCDIR" ]; then
-  echo "PKG_CPPFLAGS= -I$LIBXML_INCDIR" > src/Makevars
-  if [ "$LIBXML_LIBDIR" ]; then
-    echo "PKG_LIBS=-L$LIBXML_LIBDIR -lxml2" >> src/Makevars  
-  else
-    echo "PKG_LIBS=-lxml2" >> src/Makevars    
-  fi
-  exit 0
-fi
-
-# System libxml2
-if [ -r "/usr/include/libxml2/libxml/parser.h" ] || [ -r "/usr/local/include/libxml2/libxml/parser.h" ]; then
-  echo "PKG_LIBS=-lxml2" > src/Makevars
-  exit 0;
-fi
-
-# Find headers in xcode
-if [ $(echo "$OSTYPE" | grep "darwin") ]; then
+  echo "User specified xml2 headers in $LIBXML_INCDIR."
+elif [ -r "/usr/include/libxml2/libxml/parser.h" ]; then
+  LIBXML_INCDIR="/usr/include/libxml2/"
+elif [ -r "/usr/local/include/libxml2/libxml/parser.h" ]; then
+  LIBXML_INCDIR="/usr/local/include/libxml2/"
+elif [ -r "/opt/csw/include/libxml2/libxml/parser.h" ]; then
+  LIBXML_INCDIR="/opt/csw/include/libxml2/"
+elif [ $(echo "$OSTYPE" | grep "darwin") ]; then
   DYNLIB=$(xcodebuild -find-library xml2)
   LIBDIR=$(dirname $DYNLIB)
   XCODE=$(dirname $LIBDIR)
   LIBXML_INCDIR="$XCODE/include/libxml2"
-  if [ -r "$LIBXML_INCDIR/libxml/parser.h" ]; then
-    echo "PKG_CPPFLAGS= -I$LIBXML_INCDIR" > src/Makevars  
-    echo "PKG_LIBS=-lxml2" >> src/Makevars
-    exit 0
-  fi
+else
+  echo "Could not find libxml2. Please install libxml2-devel (rpm) or libxml2-dev (deb)."
+  exit 1
 fi
 
-echo "Could not find libxml2."
-exit 1
+echo "PKG_CPPFLAGS= -I$LIBXML_INCDIR" > src/Makevars
+if [ "$LIBXML_LIBDIR" ]; then
+  echo "PKG_LIBS=-L$LIBXML_LIBDIR -lxml2" >> src/Makevars  
+else
+  echo "PKG_LIBS=-lxml2" >> src/Makevars    
+fi
 
+exit 0
